{{- if and .Values.queryFrontend.enabled .Values.queryFrontend.autoscaling.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "prometheus-thanos.fullname" . }}-query-frontend
  labels:
    app.kubernetes.io/name: {{ include "prometheus-thanos.name" . }}-query-frontend
    helm.sh/chart: {{ include "prometheus-thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "prometheus-thanos.fullname" . }}-query-frontend
  minReplicas: {{ .Values.queryFrontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.queryFrontend.autoscaling.maxReplicas }}
{{- with .Values.querier.autoscaling.metrics }}
  metrics: 
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
