{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-thanos.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-thanos.name" . }}        
    helm.sh/chart: {{ include "prometheus-thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: cluster
    port: {{ .Values.cluster.port }}
    targetPort: cluster
  selector:
    prometheus-thanos-peer: "true"
{{- end }}