apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-thanos.fullname" . }}-compact
  labels:
    app.kubernetes.io/name: {{ include "prometheus-thanos.name" . }}-compact
    helm.sh/chart: {{ include "prometheus-thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.compact.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-thanos.name" . }}-compact
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "prometheus-thanos.name" . }}-compact
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10902"
    spec:
      containers:
        - name: {{ .Chart.Name }}-compact
          imagePullPolicy: {{ .Values.compact.image.pullPolicy }}
          image: "{{ .Values.compact.image.repository }}:{{ .Values.compact.image.tag }}"
          args:
          - compact
          - --log.level={{ .Values.compact.logLevel }}          
          - --retention.resolution-raw={{ .Values.compact.retentionResolutionRaw }}
          - --retention.resolution-5m={{ .Values.compact.retentionResolution5m }}
          - --retention.resolution-1h={{ .Values.compact.retentionResolution1h }}
          - --sync-delay={{ .Values.compact.syncDelay }}
          {{- range $key, $value := .Values.compact.additionalFlags }}
          - --{{ $key }}{{if $value }}={{ $value }}{{end}}
          {{- end }}
          {{- if .Values.compact.objStoreType }}
          - |
            --objstore.config=type: {{ .Values.compact.objStoreType }} 
            config:
            {{- toYaml .Values.compact.objStoreConfig | nindent 14 }}
          {{- end }}
          - --wait
          ports:
          - name: monitoring
            containerPort: 10902
          resources:
            {{- toYaml .Values.compact.resources | nindent 12 }}
          {{- with .Values.compact.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 14 }}
          {{- end }}
      {{- with .Values.compact.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.compact.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.compact.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.compact.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
    {{- end }}

