{{- if .Values.ruler.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-thanos.fullname" . }}-ruler
  labels:
    app.kubernetes.io/name: {{ include "prometheus-thanos.name" . }}-ruler
    helm.sh/chart: {{ include "prometheus-thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.ruler.type }}
  ports:
    - port: {{ .Values.service.ruler.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ruler.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "prometheus-thanos.name" . }}-ruler
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
