{{- if .Values.anyResources -}}
{{- range $key, $value := .Values.anyResources -}}
{{ $value }}
---
{{ end -}}
{{ else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "any-resource.fullname" . }}-dummy
  labels:
    app.kubernetes.io/name: {{ include "any-resource.name" . }}
    helm.sh/chart: {{ include "any-resource.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  foo: bar
{{- end -}}
