
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-opa-viewer
  labels:
    app.kubernetes.io/name: {{ include "kubernetes-policy-controller.name" . }}
    helm.sh/chart: {{ include "kubernetes-policy-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
