apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kubernetes-matches
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "kubernetes-policy-controller.name" . }}
    helm.sh/chart: {{ include "kubernetes-policy-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  matches.rego: |-
    package k8s
    import data.kubernetes

    matches[[kind, namespace, name, resource]] {
      resource := kubernetes[kind][namespace][name].object
    }

    matches[[kind, namespace, name, resource]] {
        resource := kubernetes[kind][namespace][name]
    }
