apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kubernetes-policymatches
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "kubernetes-policy-controller.name" . }}
    helm.sh/chart: {{ include "kubernetes-policy-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  matches.rego: |-
    package k8s
    import data.kubernetes.policies

    # Matches provides an abstraction to find policies that match the (name). 
    policymatches[[name, policy]] {
        policy := policies[name]
    }
