{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ditto-digital-twins.fullname" . }}-gateway
  labels:
    app.kubernetes.io/name: {{ include "ditto-digital-twins.name" . }}-gateway
{{ include "ditto-digital-twins.labels" . | indent 4 }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ditto-digital-twins.name" . }}-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
