apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ditto-digital-twins.fullname" . }}-gateway-secret
  labels:
    app.kubernetes.io/name: {{ include "ditto-digital-twins.name" . }}-gateway-secret
{{ include "ditto-digital-twins.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.gateway.devopsPassword }}
  devops-password: {{ .Values.gateway.devopsPassword | b64enc | quote }}
  {{- else }}
  devops-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
  {{- if .Values.gateway.statusPassword }}
  status-password: {{ .Values.gateway.statusPassword | b64enc | quote }}
  {{- else }}
  status-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
