{{- if .Values.policies.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "ditto-digital-twins.fullname" . }}-policies
  labels:
    app.kubernetes.io/name: {{ include "ditto-digital-twins.name" . }}-policies
{{ include "ditto-digital-twins.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ditto-digital-twins.name" . }}-policies
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow inner cluster communication
  - from:
    - podSelector:
        matchLabels:
          actorSystemName: {{ .Values.akka.actorSystemName }}
    ports:
    - protocol: TCP
      port: {{ .Values.akka.remoting.port }}
    - protocol: TCP
      port: {{ .Values.akka.mgmthttp.port }}
  # Open all egress
  egress:
  - {}
{{- end }}
