{{- if .Values.rbac.enabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ditto-digital-twins.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ditto-digital-twins.name" . }}
{{ include "ditto-digital-twins.labels" . | indent 4 }}
roleRef:
  kind: Role
  name: {{ include "ditto-digital-twins.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "ditto-digital-twins.serviceAccountName" . }}
{{- end -}}
