{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ditto-digital-twins.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "ditto-digital-twins.name" . }}
{{ include "ditto-digital-twins.labels" . | indent 4 }}
{{- end -}}
