{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak-client-controller.fullname" . }}
  labels:
{{ include "keycloak-client-controller.labels" . | indent 4 }}
{{- end -}}
