apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak-client-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "keycloak-client-controller.name" . }}
    helm.sh/chart: {{ include "keycloak-client-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "keycloak-client-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "keycloak-client-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REGISTRAR_KEYCLOAK_URL
              value: {{ .Values.keycloak.url | quote }}
            - name: REGISTRAR_KEYCLOAK_USER
              value: {{ .Values.keycloak.user | quote }}
            - name: REGISTRAR_KEYCLOAK_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak-client-controller.fullname" . }}
                  key: keycloakPwd
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
