apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-client-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "keycloak-client-controller.name" . }}
    helm.sh/chart: {{ include "keycloak-client-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  keycloakPwd: {{ .Values.keycloak.pwd | b64enc | quote }}
