{{- if and .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "pull-secret-distributor.fullname" . }}-crb
  labels:
    app.kubernetes.io/name: {{ include "pull-secret-distributor.name" . }}
    helm.sh/chart: {{ include "pull-secret-distributor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "pull-secret-distributor.fullname" . }}-ca
subjects:
- kind: ServiceAccount
  name: {{ template "pull-secret-distributor.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
{{- end }}
