{{- if and .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pull-secret-distributor.fullname" . }}-sa
  labels:  
    app.kubernetes.io/name: {{ include "pull-secret-distributor.name" . }}
    helm.sh/chart: {{ include "pull-secret-distributor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
