apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gcpserviceaccounts.gcp.kiwigrid.com
  labels:
    app.kubernetes.io/name: {{ include "gcp-serviceaccount-controller.name" . }}
    helm.sh/chart: {{ include "gcp-serviceaccount-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  group: gcp.kiwigrid.com
  names:
    kind: GcpServiceAccount
    plural: gcpserviceaccounts
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            bindings:
              items:
                properties:
                  resource:
                    type: string
                  roles:
                    items:
                      type: string
                    type: array
                required:
                - resource
                - roles
                type: object
              type: array
            secretName:
              type: string
            serviceAccountDescription:
              type: string
            serviceAccountIdentifier:
              type: string
          required:
          - bindings
          - serviceAccountIdentifier
          - secretName
          type: object
        status:
          properties:
            credentialKey:
              type: string
            serviceAccountMail:
              type: string
            serviceAccountPath:
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
