apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gcp-serviceaccount-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gcp-serviceaccount-controller.name" . }}
    helm.sh/chart: {{ include "gcp-serviceaccount-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gcp-serviceaccount-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: controller-manager-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gcp-serviceaccount-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - command:
        - /root/manager
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SECRET_NAME
          value: $(WEBHOOK_SECRET_NAME)
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/credentials.json
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /var/secrets
          name: secrets
          readOnly: true
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
  {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: {{ include "gcp-serviceaccount-controller.fullname" . }}
