apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-controller.fullname" . }}
  labels:
{{ include "keycloak-controller.labels" . | indent 4 }}
data:
  application-k8s.yaml: |-
    micronaut:
      metrics:
        export:
          prometheus:
            enabled: {{ .Values.prometheus.enabled }}
            step: {{ .Values.prometheus.step }}
            descriptions: {{ .Values.prometheus.descriptions }}
    endpoints:
      prometheus:
        enabled: {{ .Values.prometheus.enabled }}
    retry-rate: {{ .Values.retryRate }}
