{{- $cn := printf "%s.%s.svc.cluster.local" ( include "enmasse.fullname" . ) .Release.Namespace }}
{{- $ca := genCA "enmasse" 3650 -}}
{{- $cert := genSignedCert $cn nil nil 3650 $ca }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "enmasse.fullname" . }}-api-server-cert
  labels:
{{ include "enmasse.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}