{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "enmasse.fullname" . }}-standard-authservice
  labels:
{{ include "enmasse.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "enmasse.fullname" . }}-standard-authservice
subjects:
- kind: ServiceAccount
  name: {{ include "enmasse.fullname" . }}-standard-authservice
  namespace: {{.Release.Namespace}}
{{- end }}