{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "enmasse.fullname" . }}-api-server
  labels:
{{ include "enmasse.labels" . | indent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "services", "secrets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "configmaps/finalizers" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
  - apiGroups: [ "admin.enmasse.io" ]
    resources: [ "addressspaceplans", "addressplans", "standardinfraconfigs", "brokeredinfraconfigs", "authenticationservices", "consoleservices"]
    verbs: [ "get", "list", "watch" ]
{{- end }}