{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "enmasse.fullname" . }}-address-space-controller
  labels:
{{ include "enmasse.labels" . | indent 4 }}
{{- end }}