# Default values for secret-replicator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: kiwigrid/secret-replicator
  tag: 0.1.1
  pullPolicy: IfNotPresent
# csv list of secrets
secretList: ""
# secretList: "secret1,secret2

ignoreNamespaces: "kube-system,kube-public"
rbac:
  enabled: true

resources: {}
  # limits:
  #   cpu: 50m
  #   memory: 20Mi
  # requests:
  #   cpu: 20m
  #   memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}
