# Default values for kubernetes-policy-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  opa:
    repository: openpolicyagent/opa
    tag: 0.10.1
    pullPolicy: IfNotPresent
  kubeMgmt:
    repository: openpolicyagent/kube-mgmt
    tag: 0.6
    pullPolicy: IfNotPresent
  kubernetesPolicyController:
    repository: nikhilbh/kubernetes-policy-controller
    tag: 1.2
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# To enforce mutating policies, change to MutatingWebhookConfiguration, ValidatingWebhookConfiguration
admissionControllerKind: MutatingWebhookConfiguration
admissionControllerFailurePolicy: Ignore

generateAdmissionControllerCerts: true
admissionControllerCA: ""
admissionControllerCert: ""
admissionControllerKey: ""

admissionControllerRules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["*"]
