apiVersion: v1
kind: Service
metadata:
  name: {{ include "hono-adapter-kura.fullname" . }}
  labels:
{{ include "hono-adapter-kura.labels" . | indent 4 }}

spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
    nodePort: 31884
  - name: secure-mqtt
    port: 8883
    protocol: TCP
    targetPort: secure-mqtt
    nodePort: 30884
  selector:
    app.kubernetes.io/name: {{ include "hono-adapter-kura.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    group: {{ .Values.project.groupId }}
  {{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" )}}
  type: LoadBalancer
  {{- else }}
  type: NodePort
  {{- end}}
