apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zammad.fullname" . }}-postgresql-pass
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-pass: {{ .Values.envConfig.postgresql.pass | b64enc | quote }}
{{- if .Values.autoWizard.enabled  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "zammad.fullname" . }}-autowizard"
  labels:
    {{- include "zammad.labels" . | nindent 4 }}
type: Opaque
data:
  autowizard: {{ .Values.autoWizard.config | b64enc | b64enc | quote }}
{{ end }}
