{{- if .Values.service }}
{{- range $port := .Values.service.ports  }}
{{- $service_type := $port.type | default "ClusterIP" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluentd-elasticsearch.fullname" $ | trunc 50 }}-{{ $port.name | trunc 12 }}
  labels:
{{ include "fluentd-elasticsearch.labels" $ | indent 4 }}
    {{- if semverCompare "> 1.6" $.Capabilities.KubeVersion.GitVersion }}
    kubernetes.io/cluster-service: "true"
    {{- end }}
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  type: {{ $service_type }}
  ports:
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.port }}
      {{- if and ($port.nodePort) (eq $service_type "NodePort") }}
      nodePort: {{ $port.nodePort }}
      {{- end }}
      {{- if $port.protocol }}
      protocol: {{ $port.protocol }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "fluentd-elasticsearch.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
{{- end }}
