apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-pingdom-exporter.name" . }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-pingdom-exporter.name" . }}
    helm.sh/chart: {{ include "prometheus-pingdom-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  user: {{ .Values.pingdom.user | b64enc }}
  password: {{ .Values.pingdom.password | b64enc }}
  appId: {{ .Values.pingdom.appId | b64enc }}
  accountEmail: {{ .Values.pingdom.accountEmail | b64enc }}
