{{- if and .Values.receiver.enabled .Values.receiver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-thanos.fullname" . }}-receiver
{{- if .Values.receiver.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.receiver.serviceAccount.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "prometheus-thanos.name" . }}-receiver
    helm.sh/chart: {{ include "prometheus-thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
