---
{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "graphite.serviceAccount.name" . }}-rb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "graphite.name" . }}
    helm.sh/chart: {{ include "graphite.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ default "graphite" .Values.serviceAccount.accountName }}-role
subjects:
  - kind: ServiceAccount
    name: {{ default "graphite" .Values.serviceAccount.accountName }}
    namespace: {{ .Release.Namespace }}
{{- end }}