apiVersion: v1
appVersion: "1.0"
description: A Helm chart for a Kubernetes Controller to create secrets for GCP Service Accounts
name: gcp-serviceaccount-controller
version: 0.1.0
home: https://github.com/kiwigrid/gcp-serviceaccount-controller
sources:
- https://github.com/kiwigrid/gcp-serviceaccount-controller
maintainers:
- name: rpahli
  email: rico.pahlisch@kiwigrid.com
