apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ingress-annotator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ingress-annotator.name" . }}
    helm.sh/chart: {{ include "ingress-annotator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - update
  - patch

