kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "hawkbit-update-server.fullname" . }}
  labels:
{{ include "hawkbit-update-server.labels" . | indent 4 }}  
data:
  application.yaml: |-
{{ toYaml .Values.config.application | indent 4}}
