apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit-update-server.fullname" . }}-mysql-pass
  labels:
    app.kubernetes.io/name: {{ include "hawkbit-update-server.name" . }}
    helm.sh/chart: {{ include "hawkbit-update-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  mysql-pass: {{ .Values.env.springDatasourcePassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit-update-server.fullname" . }}-rabbitmq-pass
  labels:
    app.kubernetes.io/name: {{ include "hawkbit-update-server.name" . }}
    helm.sh/chart: {{ include "hawkbit-update-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  rabbitmq-pass: {{ .Values.env.springRabbitmqPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit-update-server.fullname" . }}-hawkbit-pass
  labels:
    app.kubernetes.io/name: {{ include "hawkbit-update-server.name" . }}
    helm.sh/chart: {{ include "hawkbit-update-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.env.springSecurityUserPassword }}
  hawkbit-pass: {{ printf "%s%s" .Values.security.passwordEncoder .Values.env.springSecurityUserPassword | b64enc | quote }}
  {{- else }}
  hawkbit-pass: {{ printf "%s%s" .Values.security.passwordEncoder (randAlphaNum 40) | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit-update-server.fullname" . }}-oidc-client-secret
  labels:
    app.kubernetes.io/name: {{ include "hawkbit-update-server.name" . }}
    helm.sh/chart: {{ include "hawkbit-update-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.oidc.enabled }}
  oidc-client-secret: {{ .Values.oidc.clientSecret | b64enc | quote }}
  {{- end }}
