apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit-update-server.fullname" . }}-mysql-pass
  labels:
    app.kubernetes.io/name: {{ include "hawkbit-update-server.name" . }}
    helm.sh/chart: {{ include "hawkbit-update-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  mysql-pass: {{ .Values.env.springDatasourcePassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit-update-server.fullname" . }}-rabbitmq-pass
  labels:
    app.kubernetes.io/name: {{ include "hawkbit-update-server.name" . }}
    helm.sh/chart: {{ include "hawkbit-update-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  rabbitmq-pass: {{ .Values.env.springRabbitmqPassword | b64enc | quote }}
