apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit-update-server.fullname" . }}
  labels:
{{ include "hawkbit-update-server.labels" . | indent 4 }}  
type: Opaque
data:
  SPRING_APPLICATION_JSON: {{ .Values.config.secrets | toJson | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hawkbit-update-server.fullname" . }}-rabbitmq-pass
  labels:
    app.kubernetes.io/name: {{ include "hawkbit-update-server.name" . }}
    helm.sh/chart: {{ include "hawkbit-update-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  rabbitmq-pass: {{ .Values.env.springRabbitmqPassword | b64enc | quote }}
