apiVersion: v2
version: 2.2.0
appVersion: "1.1.10-3"
description: Graphite metrics server
name: graphite
home: https://graphiteapp.org/
keywords:
- metrics
sources:
- https://github.com/graphite-project
- https://github.com/graphite-project/docker-graphite-statsd
maintainers:
- name: fabian-schlegel
  email: fabian.schlegel@kiwigrid.com
- name: monotek
  email: andre.bauer@kiwigrid.com
icon: https://graphiteapp.org/img/graphite-logo_color.png
