{{- if .Values.usingGCPController }}
apiVersion: gcp.kiwigrid.com/v1beta1
kind: GcpServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "stackdriver-exporter.name" . }}
    helm.sh/chart: {{ include "stackdriver-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ template "stackdriver-exporter.fullname" . }}
spec:
  serviceAccountIdentifier: {{ template "stackdriver-exporter.serviceAccountName" . }}
  serviceAccountDescription: Service account for accessing stackdriver metrics for prometheus
  secretName: {{ template "stackdriver-exporter.gcpsecretName" . }}
  bindings:
  - resource: "//cloudresourcemanager.googleapis.com/projects/{{required "gcp.projectId has to be set" .Values.gcp.projectId }}"
    roles:
    - roles/monitoring.viewer
{{ end }}
