{{- if not .Values.usingGCPController }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackdriver-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "stackdriver-exporter.name" . }}
    helm.sh/chart: {{ include "stackdriver-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}    
data:
  credentials.json: "{{ required "gcpCredentials has to be set if usingGCPController is false" .Values.gcpCredentials }}"
{{ end }}
